services:
  - type: web
    name: akilli-not-defteri
    runtime: python
    repo: https://github.com/kullaniciadi/akilli-not-defteri  # Kendi repo adresinizle değiştirin
    plan: free
    region: frankfurt  # veya singapore, ohio, oregon, frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: gizli-anahtar-2026
        generateValue: true  # Rastgele secret key oluşturur
      - key: postgresql://neondb_owner:npg_gX26oRxjOkub@ep-falling-butterfly-ad60np1i-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
        sync: false  # Elle girilecek (Neon DB bağlantısı)
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
    healthCheckPath: /
    autoDeploy: true
